### ISSUE TITLE
config not working

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.ImagePicker#3]
The following config-options is not working in the datatype when using it in non-grid-context.

- Limit
- Show title field
- Title placeholder
- Hide title
- Hide description
- Hide link

**Comment by abjerner** [comment]
Fixed in 75e4b75b9e2c54e2c8deca2d9b2e581b4072d64e and released as [v1.0.4](https://github.com/skybrud/Skybrud.ImagePicker/releases/tag/v1.0.4)
