### ISSUE TITLE
*Help wanted* Issue - ImagePicker in grid editor

### ISSUE THREAD

**Issue by FDBenevides** [skybrud/Skybrud.ImagePicker#6]
Hi Anders,

First of all, great work with all the Skybrud devs you're envolved :)

I would like to ask you a couple of questions, so this is not really an issue :)

* both ImagePicker and LinkPicker were created as an Angular Directive. It was done like that because of Angular $scope sharing and, so, allowing to use the same code as a property editor and a grid editor?

* when using it (ImagePicker/LinkPicker) as a grid editor, the developers always need to define the render view (cshtml) and configure it in the package.manifest 'render' property? (or alternatively create a cshtml with the same name as the grid editor's view name - like 'ImagePickerGridEditor' as per your example - right?) 

Thanks in advance,
And keep the excellent work ;)

**Comment by abjerner** [comment]
@FDBenevides  Thanks for the feedback :D

1. Yes, both the ImagePicker and LinkPicker are made as Angular directives so they can be reused. If you have a use case for it, you can also use the directives on your own ;)

2. Correct. We typically either have some convention on where the views should be located or use a big 
 and ugly hardcoded switch statement. But this probably comes down to preference - we rarely use `render`, but there is nothing wrong with using that instead.<br /><br />Our typical setup is somewhat described by this article: http://skrift.io/articles/archive/strongly-typed-models-in-the-umbraco-grid/

I hope that answered your questions ;)

BTW - congrats with your first GitHub issue :tada:

**Comment by FDBenevides** [comment]
ehehe Thanks @abjerner :smile: 

Yup, you've answered my questions. It was more a double checking for my side, to be confident that I had understood it well :)

PS: I've just start reading your (long) article and it seems a real valuable thing. Thank you for sharing it with me

PS#2: I think that the ImagePicker can be improved with another feature, but I will come back to you later about this...probably with a pull request ;)

Regards

**Comment by abjerner** [comment]
@FDBenevides  I will look forward to that ;)

And feel free to create another issue if you have any questions or want feedback on a possible pull request ;)
