### ISSUE TITLE
ImagePicker broke my site

### ISSUE THREAD

**Issue by lcichanowicz** [skybrud/Skybrud.ImagePicker#8]
I had a site with an existing Umbraco Grid implementation, which worked fine.  After installing the Skybrud.ImagePicker, none of my grids render.

When I render my node's grid property...
`@(Model.Content.GetPropertyValue("genericGrid").ToString())`

I get: 
`Skybrud.Umbraco.GridData.GridDataModel`

How do get my Umbraco Grid back?

**Comment by abjerner** [comment]
Hi Lee and again thanks for reporting,

As this is similar to the issue for our link picker, I've posted an answer on how to get the grid working again:

https://github.com/skybrud/Skybrud.LinkPicker/issues/7#issuecomment-413276890
